
import React from 'react';
import {
  Wand2,
  Image as ImageIcon,
  History as HistoryIcon,
  Heart,
  Copy,
  Terminal,
  Sparkles,
  Upload,
  User,
  Settings,
  Briefcase,
  Layout,
  Megaphone,
  Aperture,
  HelpCircle,
  ScanLine,
  GraduationCap,
  Layers,
  Box,
  Zap,
  Book,
  PenTool,
  Share2,
  MessageSquare,
  Bot,
  Lightbulb,
  Check,
  X,
  Moon,
  Loader,
  Lock,
  AlertTriangle,
  Film,
  Palette,
  Send,
  Shuffle,
  Combine,
  Search,
  Globe,
  ExternalLink,
  BookOpen,
  Info,
  ArrowRight,
  Link,
  Brain,
  Clapperboard,
  Play,
  ListVideo,
  Sliders,
  LayoutTemplate,
  Type,
  Droplet,
  Frame,
  Eye,
  ScanEye,
  UserCog,
  Ruler,
  Users,
  Orbit,
  Plus,
  FileJson,
  ImagePlus,
  AppWindow,
  SquareDashedBottomCode,
  Paintbrush,
  Sun,
  Focus,
  Camera,
  Award,
  Shapes,
  Component,
  Sticker,
  Car,
  Shirt,
  Store,
  CreditCard,
  Stamp,
  FileText,
  SquareUser,
  BrainCircuit,
  Workflow,
  Video,
  Shield,
  CloudRain,
  ArrowUpCircle,
  ArrowDownCircle,
  ShoppingBag,
  Home,
  UserCheck,
  Clock,
  Map,
  Anchor,
  TrendingUp,
  Circle,
  Star,
  Smile,
  Grid,
  Smartphone,
  Monitor,
  LogOut,
  ArrowLeft,
  ChevronRight,
  Code,
  Database,
  Fingerprint,
  Trash2
} from 'lucide-react';


export const Icons = {
  Wand: Wand2,
  Image: ImageIcon,
  History: HistoryIcon,
  LogOut: LogOut,

  Heart: Heart,
  Copy: Copy,
  Terminal: Terminal,
  Sparkles: Sparkles,
  Upload: Upload,
  Aperture: Aperture,
  Film: Film,
  Box: Box,
  Palette: Palette,
  MessageSquare: MessageSquare,
  Send: Send,
  Bot: Bot,
  Layers: Layers,
  Shuffle: Shuffle,
  Combine: Combine,
  Search: Search,
  Globe: Globe,
  ExternalLink: ExternalLink,
  Book: BookOpen,
  School: GraduationCap,
  GraduationCap: GraduationCap,
  Zap: Zap,
  Info: Info,
  ArrowRight: ArrowRight,
  Link: Link,
  ScanLine: ScanLine,
  Brain: Brain,
  Clapperboard: Clapperboard,
  Play: Play,
  ListVideo: ListVideo,
  Sliders: Sliders,
  Layout: LayoutTemplate,
  Type: Type,
  Pen: PenTool,
  Droplet: Droplet,
  Frame: Frame,
  Eye: Eye,
  ScanEye: ScanEye,
  Director: UserCog,
  Architect: Ruler,
  Team: Users,
  Briefcase: Briefcase,
  Orbit: Orbit,
  Megaphone: Megaphone,
  Plus: Plus,
  FileJson: FileJson,
  ImagePlus: ImagePlus,
  Website: AppWindow,
  AppWindow: AppWindow,
  Composer: SquareDashedBottomCode,
  Paintbrush: Paintbrush,
  Sun: Sun,
  Moon: Moon,
  Focus: Focus,
  User: User,
  Camera: Camera,
  Help: HelpCircle,
  Award: Award,
  Shapes: Shapes,
  Component: Component,
  Sticker: Sticker,
  Car: Car,
  Shirt: Shirt,
  Store: Store,
  CreditCard: CreditCard,
  Stamp: Stamp,
  FileText: FileText,
  IdCard: SquareUser,
  Concept: Lightbulb,
  Lightbulb: Lightbulb,
  Agent: BrainCircuit,
  Workflow: Workflow,
  Video: Video,
  Check: Check,
  X: X,
  Loader: Loader,
  Lock: Lock,
  AlertTriangle: AlertTriangle,
  Shield: Shield,
  Settings: Settings,
  CloudRain: CloudRain,
  ArrowUpCircle: ArrowUpCircle,
  ArrowDownCircle: ArrowDownCircle,
  ShoppingBag: ShoppingBag,
  Home: Home,
  UserCheck: UserCheck,
  Clock: Clock,
  Map: Map,
  Anchor: Anchor,
  BrainCircuit: BrainCircuit,
  TrendingUp: TrendingUp,
  Circle: Circle,
  Star: Star,
  Smile: Smile,
  Grid: Grid,
  Smartphone: Smartphone,
  Monitor: Monitor,
  ArrowLeft: ArrowLeft,
  ChevronRight: ChevronRight,
  Code: Code,
  Database: Database,
  Fingerprint: Fingerprint,
  Trash: Trash2
};