-- 1. Add 'content' column if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'library_prompts' AND column_name = 'content') THEN
        ALTER TABLE public.library_prompts ADD COLUMN content text;
    END IF;
END $$;

-- 2. Insert 70 High-Quality Prompts
-- We use a temporary table or direct insert. Direct insert is fine.
-- User ID: 27d483ed-f5f4-4616-a98e-e640b98d2398

INSERT INTO public.library_prompts (user_id, title, category, content, concept, style, tag_list, is_verified, is_public, likes_count)
VALUES
-- GERAL (General)
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Cena de Rua em Tóquio', 'General', 'Candid street photography of a busy Tokyo crossing in Shinjuku at dusk, Rain-soaked asphalt reflecting neon lights, motion blur of pedestrians, cinematic grain, Shot on Leica M6, 35mm film stock, Kodak Portra 400 colors, high contrast, vignette.', 'Fotografia de rua "Slice of Life" com atmosfera e movimento.', 'Photography', ARRAY['street', 'tokyo', 'neon', 'candid'], true, true, 120),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Natureza Morta Barroca', 'General', 'Baroque still life composition in the style of Caravaggio, a rustic woven basket overflowing with pomegranates and grapes on a dark oak table, dramatic chiaroscuro lighting, a half-peeled lemon with textured pith, a pewter goblet reflecting the scene, dark background, oil painting aesthetic, ultra-detailed textures --ar 4:5', 'Estudo de luz e textura inspirado em Caravaggio.', 'Oil Painting', ARRAY['art', 'baroque', 'fruit', 'chiaroscuro'], true, true, 95),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Retrato de Gato Maine Coon', 'General', 'Studio portrait of a Maine Coon cat, majesty and elegance, backlit by a soft rim light highlighting the fluffiness of the fur, jet black background, heterochromia eyes (one blue, one gold), macro photography, sharp focus on eyes, 8k resolution, detailed whiskers --ar 1:1', 'Isolamento de sujeito com Rim Light.', 'Photography', ARRAY['animal', 'cat', 'studio', 'rim-light'], true, true, 210),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Café da Manhã Flat Lay', 'General', 'Overhead flat lay photography of a cozy Sunday breakfast, steaming cup of artisan coffee with latte art, an open book with visible text, croissant on a ceramic plate, soft morning sunlight casting shadows through window blinds (gobo effect), aesthetic and minimalist, high key lighting --ar 3:4', 'Composição lifestyle com Luz de Persiana (Gobo).', 'Photography', ARRAY['food', 'lifestyle', 'flat-lay', 'cozy'], true, true, 150),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Editorial Vintage 70s', 'General', '1970s fashion editorial snapshot, Polaroid aesthetic, a group of friends laughing in a vintage convertible car, windblown hair, lens flare, warm sepia tones, faded colors, nostalgic atmosphere, California coast highway background, authentic vintage look --ar 4:3', 'Estética retrô com filme degradado.', 'Photography', ARRAY['vintage', '70s', 'polaroid', 'fashion'], true, true, 180),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Chuva Cinematográfica', 'General', 'Cinematic shot of a solitary figure holding a transparent umbrella in heavy rain, watching a city skyline from a distance, droplets running down the camera lens, bokeh lights in the background, cool blue color palette, moody and pensive atmosphere, shallow depth of field --ar 16:9', 'Atmosfera melancólica e imersão visual.', 'Cinematic', ARRAY['rain', 'moody', 'city', 'cinematic'], true, true, 140),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Sala de Estar Boho', 'General', 'Interior design photography of a bohemian living room, macramé wall hangings, abundance of indoor plants (monstera, ferns), warm fairy lights, patterned persian rugs, sunlight streaming in, cozy and cluttered but stylish, wide angle shot, architectural digest style --ar 16:9', 'Design de interiores rico em texturas.', 'Photography', ARRAY['interior', 'boho', 'cozy', 'plants'], true, true, 130),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Splash de Morango', 'General', 'High-speed photography of a strawberry falling into milk, creating a majestic crown splash, droplets suspended in air, macro focus, pure white background, commercial lighting, crisp details, zero motion blur, refreshing and dynamic --ar 1:1', 'Fotografia high-speed publicitária.', 'Photography', ARRAY['food', 'splash', 'macro', 'advertising'], true, true, 110),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Biblioteca Antiga', 'General', 'Atmospheric shot of an ancient library, towering shelves filled with leather-bound books, floating dust particles in shafts of sunlight (God rays), ladder resting on shelves, scholarly atmosphere, dark academia aesthetic, hyper-detailed textures of paper and wood --ar 2:3', 'Ambiência volumétrica e detalhamento.', 'Cinematic', ARRAY['library', 'dark-academia', 'atmospheric', 'books'], true, true, 200),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Mural de Graffiti Urbano', 'General', 'Urban photography of a vibrant graffiti mural on a textured brick wall, spray paint drips, peeling paint layers, harsh sunlight casting sharp shadows from a nearby fire escape, vivid colors (cyan, magenta, yellow), realistic urban decay texture, 8k resolution --ar 16:9', 'Texturas urbanas realistas.', 'Photography', ARRAY['street-art', 'urban', 'texture', 'graffiti'], true, true, 90),

-- RETRATO (Portrait)
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Retrato Hyper-Real', 'Portrait', 'Extreme close-up portrait of a young woman with freckles and unplucked eyebrows, Soft window light from the left, creating a gentle gradient on the face, catchlight in eyes, Visible skin pores, peach fuzz on cheeks, slight skin unevenness, shot on 85mm lens f/1.8, Sony A7R IV.', 'Pele realista com imperfeições naturais.', 'Photography', ARRAY['portrait', 'realistic', 'close-up', 'human'], true, true, 250),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Marinheiro Idoso', 'Portrait', 'Portrait of an elderly sailor with a weathered, sun-damaged face, deep wrinkles etched by time, intense blue eyes looking at the horizon, wearing a thick cable-knit sweater, storm clouds in background, dramatic side lighting enhancing texture, raw and gritty style, Steve McCurry aesthetic --ar 2:3', 'Narrativa visual através de texturas faciais.', 'Photography', ARRAY['portrait', 'man', 'dramatic', 'storytelling'], true, true, 175),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Hacker Cyberpunk', 'Portrait', 'Futuristic cyberpunk portrait of a hacker, illuminated by the glow of multiple computer screens, neon pink and blue reflections on sweaty skin, wearing augmented reality glasses, dark room background with bokeh servers, cinematic teal and orange grading, high ISO grain style --ar 9:16', 'Iluminação complexa em pele suada.', 'Sci-Fi', ARRAY['cyberpunk', 'neon', 'tech', 'portrait'], true, true, 220),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Beleza High Fashion', 'Portrait', 'High-end beauty photography, fashion model with avant-garde graphic eyeliner, glossy lips, slicked-back hair, butterfly lighting setup (glamour shot), clean background, sharp focus on eyelashes and lips, retouching style of Vogue magazine, crisp definition --ar 4:5', 'Iluminação de estúdio "Butterfly".', 'Photography', ARRAY['fashion', 'beauty', 'makeup', 'studio'], true, true, 160),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Guerreiro Maasai', 'Portrait', 'Documentary portrait of a Maasai warrior in traditional attire, vibrant red shuka cloth, intricate beaded jewelry, standing in the African savanna at golden hour, warm natural light, dignified expression, depth of field separating subject from acacia trees, National Geographic style, authentic --ar 2:3', 'Retrato documental étnico autêntico.', 'Photography', ARRAY['documentary', 'culture', 'africa', 'portrait'], true, true, 195),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Dupla Exposição Tempestade', 'Portrait', 'Double exposure art portrait, silhouette of a man''s side profile combined with a raging ocean storm, waves crashing inside the silhouette, seagulls flying, moody blue and grey tones, isolated on white background, fine art photography, surreal and emotive --ar 1:1', 'Arte surrealista de silhueta.', 'Artistic', ARRAY['double-exposure', 'surreal', 'ocean', 'art'], true, true, 230),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Criança Sorrindo', 'Portrait', 'Candid shot of a toddler laughing uncontrollably, messy hair, chocolate stains on face, playing in a sunlit garden, backlit by late afternoon sun causing lens flares, soft focus background of flowers, capturing pure joy, lifestyle photography, high shutter speed --ar 1:1', 'Captura de emoção espontânea e inocência.', 'Photography', ARRAY['kids', 'smile', 'happy', 'candid'], true, true, 190),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Detetive Noir', 'Portrait', 'Classic Film Noir portrait of a detective, smoking a cigarette (smoke swirling), wearing a fedora hat, heavy shadows obscuring eyes (chiaroscuro), dramatic Venetian blind shadows cast across the face, high contrast black and white, grainy film texture, mysterious atmosphere --ar 2:3', 'Estilo Noir clássico preto e branco.', 'Cinematic', ARRAY['noir', 'bnw', 'mystery', 'detective'], true, true, 145),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Princesa Élfica', 'Portrait', 'Hyper-realistic portrait of an ethereal elf princess, pale skin with faint iridescent scales, long silver hair flowing in water, glowing violet eyes, wearing intricate organic silver jewelry, bioluminescent forest background, soft dreamy lighting, fantasy concept art meets photography, 8k --ar 9:16', 'Fantasia realista e etérea.', 'Fantasy', ARRAY['elf', 'fantasy', 'magic', 'ethereal'], true, true, 260),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Headshot Corporativo', 'Portrait', 'Professional corporate headshot of a confident CEO, diverse female, wearing a sharp tailored navy blazer, modern glass office building background (blurred), natural daylight, approachable smile, direct eye contact, high quality LinkedIn profile photo style, trustworthy and leadership vibe --ar 1:1', 'Retrato de negócios profissional.', 'Photography', ARRAY['business', 'professional', 'linkedin', 'corporate'], true, true, 115),

-- PAISAGEM (Landscape)
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Montanhas Alpinas', 'Landscape', 'Majestic snow-capped mountain range reflecting in a crystal clear alpine lake, Alpenglow lighting turning peaks pink and purple at sunrise, soft mist on water, Foreground of blooming wildflowers and pine trees, wide angle lens, high depth of field.', 'Majestade natural com Alpenglow.', 'Photography', ARRAY['nature', 'mountains', 'landscape', 'sunrise'], true, true, 205),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Cidade Solarpunk', 'Landscape', 'Solarpunk utopian city, harmonious blend of high-tech architecture and lush nature, vertical forests on glass skyscrapers, flying wind turbines, clear blue sky with fluffy clouds, bright and optimistic atmosphere, aerial drone shot, sustainable living aesthetic, highly detailed --ar 16:9', 'Futurismo otimista e ecológico.', 'Sci-Fi', ARRAY['solarpunk', 'scifi', 'city', 'future'], true, true, 240),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Floresta Sombria', 'Landscape', 'Dark fantasy ancient forest, twisted gnarled trees with roots covering the ground, thick rolling fog, glowing blue will-o''-the-wisps floating in the air, moonlight filtering through canopy, mysterious and eerie atmosphere, cinematic lighting, concept art style, detailed textures of bark and moss --ar 16:9', 'Ambiência de fantasia dark.', 'Fantasy', ARRAY['forest', 'dark', 'fantasy', 'fog'], true, true, 185),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Deserto Apocalíptico', 'Landscape', 'Post-apocalyptic desert wasteland, ruins of a buried city protruding from sand dunes, rusted metal structures, harsh midday sun creating sharp shadows, heat haze distortion, vibrant orange and teal sky, cinematic wide shot, grit and dust texture, survivalist aesthetic --ar 21:9', 'Estética desolada "Mad Max".', 'Cinematic', ARRAY['desert', 'apocalypse', 'wasteland', 'cinematic'], true, true, 165),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Praia Tropical Aérea', 'Landscape', 'Aerial top-down view of a tropical beach, gradient of turquoise water crashing onto white sand, palm tree shadows stretching on the beach, coral reefs visible under water, vibrant and relaxing, travel photography style, high resolution, summer vibes --ar 3:4', 'Vista top-down texturizada.', 'Photography', ARRAY['beach', 'tropical', 'aerial', 'summer'], true, true, 190),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Sala Minimalista Oceânica', 'Landscape', 'Modern minimalist living room with floor-to-ceiling windows overlooking the ocean, open concept, monochromatic beige color palette, expensive italian furniture, soft diffuse daylight, architectural visualization, clean lines, clutter-free, serene atmosphere, 8k render --ar 16:9', 'Luxo minimalista e arquitetura.', '3D Render', ARRAY['interior', 'minimalist', 'luxury', 'archviz'], true, true, 210),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Rua Cyberpunk Chuvosa', 'Landscape', 'Rainy cyberpunk street at night, neon signs reflecting in puddles (cyan and magenta), towering holographic advertisements, steam rising from vents, crowded with futuristic pedestrians, cinematic blade runner aesthetic, volumetric fog, high contrast, immersive perspective --ar 16:9', 'Clássico sci-fi com reflexos urbanos.', 'Sci-Fi', ARRAY['cyberpunk', 'neon', 'rain', 'city'], true, true, 280),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Inverno Nórdico', 'Landscape', 'Nordic winter landscape, solitary red wooden cabin in a vast field of snow, Aurora Borealis (Northern Lights) illuminating the night sky with green swirls, stars visible, long exposure photography, majestic and peaceful, cold color temperature, sharp details --ar 16:9', 'Contraste de cores na neve.', 'Photography', ARRAY['winter', 'snow', 'aurora', 'nature'], true, true, 195),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Jardim Zen Japonês', 'Landscape', 'Traditional Japanese Zen garden, raked sand patterns (kare-sansui), moss-covered rocks, cherry blossom trees (sakura) shedding petals, soft spring sunlight, wooden bridge over a koi pond, peaceful and meditative, highly detailed nature photography --ar 3:2', 'Equilíbrio e detalhe botânico.', 'Photography', ARRAY['japan', 'garden', 'zen', 'nature'], true, true, 160),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Ruínas Subaquáticas', 'Landscape', 'Mysterious underwater ruins of an ancient civilization, overgrown with coral and algae, shafts of sunlight piercing the deep water (god rays), schools of exotic fish swimming through arches, dark blue depths, atmospheric and exploration themed, National Geographic style --ar 16:9', 'Atmosfera e iluminação subaquática.', 'Fantasy', ARRAY['underwater', 'ruins', 'ocean', 'mystery'], true, true, 175),

-- PERSONAGEM (Character)
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Sheet de Guerreiro RPG', 'Character', 'Character design sheet of a rugged fantasy warrior, full body, multiple angles (front, side, back), Wearing battered leather armor and fur cloak, carrying a heavy greatsword on back, utility belt with potions, Concept art style, neutral grey background, flat lighting for detail visibility, in the style of Dungeons & Dragons rulebook art.', 'Design técnico para modelagem/concept.', 'Concept Art', ARRAY['rpg', 'warrior', 'concept-art', 'character-sheet'], true, true, 230),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Caçador de Recompensas Sci-Fi', 'Character', 'Dynamic action shot of a sci-fi bounty hunter sliding across the floor while firing dual laser pistols, futuristic combat suit with glowing accents, sparks flying, motion blur background of a spaceship corridor, intense expression, cinematic lighting, comic book cover art style --ar 2:3', 'Ação dinâmica e movimento.', 'Comic Book', ARRAY['scifi', 'action', 'hero', 'dynamic'], true, true, 195),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Dragão Bebê Pixar', 'Character', 'Adorable 3D animated character, a fluffy baby dragon with big expressive eyes, sitting on a pile of gold coins, soft scales texture, warm studio lighting, Pixar movie style, renderman engine, cute and charming, vibrant colors, 4k resolution --ar 1:1', 'Estilo "fofo" high-end render.', '3D Render', ARRAY['cute', 'dragon', 'pixar', '3d'], true, true, 300),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Vilão Cibernético', 'Character', 'Full body shot of a menacing cybernetic villain, fusion of flesh and black metal machinery, glowing red optical sensors, long trench coat billowing in wind, standing in rain, dark moody atmosphere, intricate mechanical details, cyberpunk horror aesthetic, unreal engine 5 render --ar 9:16', 'Design de horror tecnológico.', 'Sci-Fi', ARRAY['villain', 'cyberpunk', 'robot', 'dark'], true, true, 210),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Garota Mágica Anime', 'Character', 'Anime character design of a magical girl, intricate frilly dress with celestial motifs (stars and moons), holding a glowing magical staff, dynamic floating pose, vibrant pastel colors, cel-shaded style, high quality anime art like Genshin Impact, detailed background of a sky castle --ar 2:3', 'Estética anime vibrante e detalhada.', 'Anime', ARRAY['anime', 'magical-girl', 'genshin', 'cel-shaded'], true, true, 280),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Inventor Steampunk', 'Character', 'Steampunk inventor character, wearing brass goggles and leather aviator cap, mechanical arm with gears and pistons, holding a complex clockwork device, Victorian era clothing, sepia toned background with steam and cogwheels, detailed illustration, intricate textures --ar 3:4', 'Texturas de materiais industriais.', 'Illustration', ARRAY['steampunk', 'inventor', 'victorian', 'gears'], true, true, 150),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Monstro do Mar Profundo', 'Character', 'Terrifying deep sea monster concept art, bioluminescent scales, multiple rows of sharp teeth, translucent skin revealing internal organs, dark aquatic environment, horror theme, realistic creature design, Lovecraftian aesthetic, hyper-detailed --ar 16:9', 'Creature design biológico e grotesco.', 'Concept Art', ARRAY['monster', 'creature', 'horror', 'lovecraft'], true, true, 165),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Herói de Quadrinhos', 'Character', 'Comic book cover art of a superhero flying through clouds, muscular anatomy, tight spandex suit with emblem, dramatic perspective (worm''s eye view), bold ink lines, vibrant primary colors, halftone dot shading pattern, dynamic and energetic, Marvel comics style --ar 2:3', 'Estilo clássico de HW com hachuras.', 'Comic Book', ARRAY['superhero', 'comic', 'marvel', 'dynamic'], true, true, 190),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Samurai Cyberpunk', 'Character', 'Historical fiction character, a Samurai warrior wearing traditional armor but with futuristic neon katana, standing in a cherry blossom forest at night, fusion of Edo period and Cyberpunk, cinematic lighting, serious expression, highly detailed armor patterns --ar 2:3', 'Fusão de épocas e estilos.', 'Sci-Fi', ARRAY['samurai', 'cyberpunk', 'neon', 'fusion'], true, true, 225),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Taverneiro Anão', 'Character', 'Friendly tavern keeper NPC, stout dwarf wiping a mug, warm fireplace lighting in background, wearing an apron over rustic clothes, ruddy cheeks and thick beard, inviting atmosphere, fantasy oil painting style, detailed background of bottles and barrels --ar 3:4', 'Personagem com contexto e ambientação.', 'Fantasy', ARRAY['dwarf', 'fantasy', 'npc', 'tavern'], true, true, 140),

-- ABSTRATO (Abstract)
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Arte Fluida Dourada', 'Abstract', 'Swirling macro fluid art, mixture of gold metallic ink and black oil, Marble texture, turbulent flow patterns, iridescent sheen, high gloss finish, Abstract expressionism, mesmerizing detail, 8k resolution, wallpaper aesthetic.', 'Física de fluidos e contraste de materiais.', 'Abstract', ARRAY['fluid', 'gold', 'abstract', 'texture'], true, true, 200),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Fractal Mandelbulb 3D', 'Abstract', 'Intricate 3D fractal structure, Mandelbulb 3D style, infinite geometric patterns repeating, glowing neon edges against dark background, mathematical perfection, sci-fi abstract, depth of field drawing eye to center, mesmerizing and complex --ar 16:9', 'Geometria matemática complexa.', '3D Render', ARRAY['fractal', 'math', 'abstract', 'neon'], true, true, 180),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Light Painting', 'Abstract', 'Long exposure light painting, vibrant ribbons of light (cyan, magenta, lime) floating in void, curving and twisting, smooth gradients, abstract energy flow, pure black background, high contrast, minimalist but dynamic --ar 16:9', 'Rastros de luz e movimento etéreo.', 'Photography', ARRAY['light', 'abstract', 'neon', 'long-exposure'], true, true, 160),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Glitch Art', 'Abstract', 'Abstract glitch art, distorted data mosh effect, pixel sorting, broken TV screen noise, vibrant neon colors clashing, cyber chaos, corrupted digital file aesthetic, modern art, edgy and raw --ar 2:3', 'Estética do erro e distorção digital.', 'Digital Art', ARRAY['glitch', 'error', 'abstract', 'cyber'], true, true, 145),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Sonho Surrealista (Dalí)', 'Abstract', 'Surrealist dreamscape inspired by Salvador Dalí, melting clocks draping over dead trees in a vast desert, floating elephants with long spindly legs, strange juxtaposition of objects, dreamlike atmosphere, vivid blue sky, oil painting style --ar 16:9', 'Juxtaposição onírica e ilógica.', 'Artistic', ARRAY['surreal', 'dali', 'dream', 'abstract'], true, true, 190),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Vidro Dicróico', 'Abstract', 'Abstract composition of dichroic glass geometric shapes, prisms refracting light into rainbows, sharp angles, clean white background, caustics on floor, modern design, ray tracing render, colorful and prismatic --ar 1:1', 'Refração de luz e cor.', '3D Render', ARRAY['glass', 'prism', 'abstract', 'colorful'], true, true, 175),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Topografia de Papel', 'Abstract', 'Topographic map style paper cut art, multiple layers of colored paper (shades of blue) creating depth, organic curved lines representing elevation, soft shadows between layers, abstract aerial view, craft aesthetic, minimalist --ar 4:3', 'Profundidade simulada com camadas.', 'Craft', ARRAY['paper', 'abstract', 'texture', 'blue'], true, true, 155),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Explosão Holi', 'Abstract', 'Explosion of vibrant colored powder (Holi festival style), freezing motion of particles, clouds of red, yellow and blue dust colliding, black background for contrast, dynamic energy, macro details of dust grains, high speed photography --ar 16:9', 'Congelamento de partículas.', 'Photography', ARRAY['color', 'explosion', 'abstract', 'energy'], true, true, 210),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Padrão Memphis 80s', 'Abstract', 'Seamless Memphis design pattern, geometric shapes (squiggles, triangles, dots) in pastel colors on white background, 1980s retro aesthetic, flat vector style, playful and chaotic, pop art influence, suitable for wallpaper --tile', 'Caos geométrico retrô.', 'Vector', ARRAY['pattern', '80s', 'retro', 'abstract'], true, true, 130),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Bioluminescência Celular', 'Abstract', 'Abstract organic macro texture, bioluminescent cells glowing in dark, neural network patterns, intricate web of connections, pulsing light, sci-fi biology, mysterious and beautiful, 8k detail --ar 16:9', 'Padrões orgânicos complexos.', 'Sci-Fi', ARRAY['bio', 'abstract', 'glow', 'organic'], true, true, 220),

-- RENDERIZAÇÃO 3D (3D Render)
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Quarto Gamer Isométrico', '3D Render', 'Tiny cute isometric gamer room in a cutaway box style, Detailed desk setup with multiple monitors, neon LED strips, plush bean bag, messy but cozy, 3D Blender render, orthographic view, clay material finish, soft global illumination, pastel colors, high poly.', 'Estilo "Cutaway Box" aconchegante.', '3D Render', ARRAY['isometric', 'room', 'cute', '3d'], true, true, 290),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Ícone Glassmorphism', '3D Render', '3D glassmorphism icon of a music note, frosted glass texture with blur, multilayered transparency, soft pastel gradients (pink to blue), floating in air, soft drop shadow, high gloss edge highlights, iOS app icon style, clean background --ar 1:1', 'Transparência fosca moderna.', '3D Render', ARRAY['icon', 'glass', 'ui', 'modern'], true, true, 185),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Robô de Massinha', '3D Render', 'Cute claymorphism character of a smiling robot, made of plasticine/clay texture, fingerprints visible on surface for realism, soft rounded edges, vibrant colors, stop-motion animation aesthetic, studio lighting, simple background --ar 1:1', 'Textura tátil com imperfeições.', '3D Render', ARRAY['clay', 'cute', 'robot', '3d'], true, true, 215),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Beco Cyberpunk UE5', '3D Render', 'Unreal Engine 5 render of a futuristic alleyway, wet pavement reflecting neon signs, highly detailed textures (Megascans), volumetric fog, ray tracing enabled, lumen global illumination, cinematic camera angle, photorealistic game asset style --ar 16:9', 'Fidelidade gráfica Next-Gen.', '3D Render', ARRAY['cyberpunk', 'ue5', 'realistic', 'environment'], true, true, 275),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Relógio Exploded View', '3D Render', 'Exploded view 3D render of a mechanical watch, all parts (gears, springs, screws) suspended in air in perfect order, technical visualization, metallic textures (gold, steel, brass), clean studio lighting, depth of field highlighting the center, engineering precision --ar 3:2', 'Visualização técnica de complexidade.', '3D Render', ARRAY['tech', 'watch', 'engineering', '3d'], true, true, 195),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Camping Low Poly', '3D Render', 'Low poly 3D landscape of a camping site at night, geometric pine trees, triangular mountains, glowing tent, campfire with low poly smoke, soft ambient occlusion shadows, minimal art style, charming and simple, pastel night colors --ar 16:9', 'Minimalismo geométrico.', '3D Render', ARRAY['low-poly', 'minimalist', 'camping', '3d'], true, true, 170),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Escultura Mármore e Ouro', '3D Render', 'Abstract 3D sculpture composition, spherical shapes made of white Carrara marble and polished liquid gold, contrasting textures (matte vs glossy), physically based rendering (PBR), luxury art installation, elegant studio lighting, soft shadows --ar 4:5', 'Contraste de materiais PBR luxuosos.', '3D Render', ARRAY['art', 'luxury', 'gold', 'marble'], true, true, 180),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Knolling de Câmera', '3D Render', '3D render knolling of vintage camera gear, lenses, film rolls, and tools arranged neatly on a grid cutting mat, top-down view, realistic textures of leather and metal, balanced composition, soft even lighting, highly detailed product visualization --ar 1:1', 'Organização visual e texturas.', '3D Render', ARRAY['knolling', 'photography', 'organized', '3d'], true, true, 165),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Cidade Tilt-Shift', '3D Render', 'Tilt-shift 3D render of a bustling city street, looking like a miniature toy set, distinct blur at top and bottom, high saturation, plastic toy cars and people, isometric angle, diorama aesthetic, playful and vibrant --ar 16:9', 'Efeito de miniatura óptica.', '3D Render', ARRAY['city', 'miniature', 'tilt-shift', '3d'], true, true, 205),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Caveira de Cristal', '3D Render', 'Crystal skull 3D render, carved from amethyst, internal cracks and flaws catching light, glowing from within, dark mystical background, caustic light patterns on table, octane render, spiritual and edgy aesthetic --ar 2:3', 'Refração de luz e materiais translúcidos.', '3D Render', ARRAY['crystal', 'skull', 'octane', '3d'], true, true, 240),

-- LOGOTIPO (Logo)
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Logo Minimalista Raposa', 'Logo', 'Minimalist vector logo of a fox head, constructed from simple geometric shapes (triangles and circles), Flat design, solid orange color, no gradients, no shading, clean thick lines, Isolated on white background, Paul Rand style, scalable for app icon.', 'Simplicidade geométrica funcional.', 'Vector', ARRAY['logo', 'fox', 'minimalist', 'vector'], true, true, 195),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Espaço Negativo Urso', 'Logo', 'Clever negative space logo design, silhouette of a mountain peak containing a hidden silhouette of a bear inside the white space, monochrome black and white, minimalist, gestalt principle, smart and iconic, vector graphics --ar 1:1', 'Uso inteligente do espaço negativo.', 'Vector', ARRAY['logo', 'negative-space', 'bear', 'clever'], true, true, 210),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Emblema Café Vintage', 'Logo', 'Vintage line art emblem logo for a coffee shop, illustration of a coffee bean and sun rays, circular border with text placeholders, mono-weight lines, rustic aesthetic, badge style, vector, black ink on white background --ar 1:1', 'Estilo linear artesanal.', 'Vector', ARRAY['logo', 'coffee', 'vintage', 'badge'], true, true, 160),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Mascote E-Sports Tubarão', 'Logo', 'Aggressive e-sports mascot logo of a shark, bold thick outlines, vibrant neon blue and purple colors, vector illustration style, dynamic pose, angry expression, clean background, suitable for twitch streamer branding --ar 1:1', 'Traços grossos e cores vibrantes.', 'Vector', ARRAY['logo', 'esports', 'shark', 'mascot'], true, true, 230),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Tech Wordmark "A"', 'Logo', 'Futuristic tech wordmark logo, letter ''A'' stylized as a rocket or arrow, sharp angular font, gradient of cyan to blue, modern and sleek, saas startup branding, vector style, clean white background --ar 3:1', 'Tipografia estilizada futurista.', 'Vector', ARRAY['logo', 'tech', 'startup', 'letter'], true, true, 175),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'App Icon Onda', 'Logo', 'Modern abstract app icon logo, fluid shape resembling a wave, vibrant gradient colors (purple to orange), rounded corners squircle shape, ios design aesthetic, glossy finish, minimalist symbol --ar 1:1', 'Design mobile moderno e gradiente.', 'Vector', ARRAY['logo', 'icon', 'app', 'modern'], true, true, 190),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Brasão Moderno', 'Logo', 'Modern heraldic crest logo, simplified lion and unicorn rampant, geometric shield shape, flat vector style, royal blue and gold colors, minimal details, university or luxury brand identity, symmetrical composition --ar 1:1', 'Tradição simplificada.', 'Vector', ARRAY['logo', 'crest', 'luxury', 'royal'], true, true, 140),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Logo Lótus Line Art', 'Logo', 'Elegant continuous line art logo of a lotus flower, one single fluid stroke, minimalist and feminine, spa and wellness branding, black thin line on pastel pink background, sophisticated and clean --ar 1:1', 'Delicadeza de linha contínua.', 'Vector', ARRAY['logo', 'lotus', 'line-art', 'wellness'], true, true, 155),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Logo Lobo Low Poly', 'Logo', 'Low poly geometric animal logo, head of a wolf made of colorful triangles, prismatic color palette, sharp edges, modern vector art, faceted design, creative agency branding, white background --ar 1:1', 'Mosaico geométrico vibrante.', 'Vector', ARRAY['logo', 'low-poly', 'wolf', 'colorful'], true, true, 185),
('27d483ed-f5f4-4616-a98e-e640b98d2398', 'Símbolo Infinito 3D', 'Logo', 'Stylized infinity symbol logo, interwoven loops creating a 3D knot effect, gradient shading for depth, corporate blue colors, symbol of connectivity and eternity, modern vector icon, clean design --ar 1:1', 'Abstração corporativa com profundidade.', 'Vector', ARRAY['logo', 'infinity', '3d', 'corporate'], true, true, 165);
